import Head from "next/head";
import { Fragment } from "react";
import MovieDetail from "@/components/Movies/MovieDetail";
import { useRouter } from "next/router";

export default function Detail() {
  const router = useRouter();
  const { imdbId } = router.query;
  const imdb = Array.isArray(imdbId) ? imdbId[0] : imdbId;

  return (
    <Fragment>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MovieDetail imdbId={imdb} />
    </Fragment>
  );
}
